/* 
PROJECT EULER 

Problem 2 - 01/05/2020

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
  let evenSum = 2;
  let num1 = 1;
  let num2 = 2;
  let temp;
  if (n <= 1) return evenSum;
  for (let i = 3; i <= n; i++) {
    temp = num2;
    num2 = num1 + num2;
    num1 = temp;
    num2 % 2 ? null : (evenSum += num2);
  }
  return evenSum;
}

console.log(fiboEvenSum(10));
